#./build/X86/gem5.opt ./configs/example/se.py -c ./microbench --caches --l2cache --cpu-type=O3_X86_icelake_1   --mem-type=DDR4_2400_16x4 --mem-size=64GB --mem-channels=2  --enable-microop-cache --enable-micro-fusion  --lvpredType=fa3p --dynamicThreshold=5 --constantThreshold=3 --predictionConfidenceThreshold=5 --l3cache
#./build/X86/gem5.opt --debug-flags=MemDepUnit,LVP,Exec,Decoder,O3CPUAll,Fetch,X86,Commit,IEW,Branch,FA3P --debug-file=valePred_full.out --debug-start=60000000 ./configs/example/se.py -m 70000000 -c ./microbench --caches --l2cache --cpu-type=O3_X86_icelake_1   --mem-type=DDR4_2400_16x4 --mem-size=64GB --mem-channels=2  --enable-microop-cache --enable-micro-fusion  --lvpredType=fa3p --dynamicThreshold=5 --constantThreshold=3 --predictionConfidenceThreshold=5 --l3cache
#./build/X86/gem5.opt --debug-flags=LVP,Exec,FA3P,IEW --debug-file=valePred_full.out ./configs/example/se.py -c ./microbench --caches --l2cache --cpu-type=O3_X86_icelake_1   --mem-type=DDR4_2400_16x4 --mem-size=64GB --mem-channels=2  --enable-microop-cache --enable-micro-fusion  --lvpredType=fa3p --dynamicThreshold=5 --constantThreshold=3 --predictionConfidenceThreshold=5 --l3cache
#./build/X86/gem5.opt --debug-flags=Exec --debug-file=valePred_exec.out ./configs/example/se.py -c ./microbench --caches --l2cache --cpu-type=O3_X86_icelake_1   --mem-type=DDR4_2400_16x4 --mem-size=64GB --mem-channels=2  --enable-microop-cache --enable-micro-fusion  --lvpredType=fa3p --dynamicThreshold=5 --constantThreshold=3 --predictionConfidenceThreshold=5 --l3cache
#./build/X86/gem5.opt --outdir=m5out_arith --debug-flags=SuperOpSanityCheck --debug-file=valePred_sanity.out ./configs/example/se.py -c ./microbench --caches --l2cache --cpu-type=O3_X86_icelake_1   --mem-type=DDR4_2400_16x4 --mem-size=64GB --mem-channels=2  --enable-microop-cache --enable-micro-fusion --predictingArithmetic=1 --enableValuePredForwarding --lvpredType=fa3p --dynamicThreshold=5 --constantThreshold=3 --predictionConfidenceThreshold=5 --l3cache > arith.out 2> arith.debug
#./build/X86/gem5.opt --outdir=m5out_valuePred --debug-flags=SuperOpSanityCheck --debug-file=valePred_sanity.out ./configs/example/se.py -c ./microbench --caches --l2cache --cpu-type=O3_X86_icelake_1   --mem-type=DDR4_2400_16x4 --mem-size=64GB --mem-channels=2  --enable-microop-cache --enable-micro-fusion --enableValuePredForwarding --lvpredType=fa3p --dynamicThreshold=5 --constantThreshold=3 --predictionConfidenceThreshold=5 --l3cache > lvpred.out 2> lvpred.err
#time ./build/X86/gem5.opt --outdir=m5out_valuePred --debug-flags=SuperOpSanityCheck --debug-file=valePred_sanity.out ./configs/example/se.py -c ./microbench --caches --l2cache --cpu-type=O3_X86_icelake_1   --mem-type=DDR4_2400_16x4 --mem-size=64GB --mem-channels=2  --enable-microop-cache --enable-micro-fusion --predictingArithmetic=1 --enableValuePredForwarding --lvpredType=fa3p --dynamicThreshold=5 --constantThreshold=3 --predictionConfidenceThreshold=5 --l3cache > valuePred.out 2>valuePred.err
./build/X86/gem5.opt ./configs/example/se.py -c ./microbench --caches --l2cache --cpu-type=O3_X86_icelake_1 --mem-type=DDR4_2400_16x4 --mem-size=64GB --mem-channels=2 --enable-microop-cache --uopCacheNumSets=48 --uopCacheNumWays=16 --uopCacheNumUops=6 --enable-micro-fusion --l3cache --lvpredType=eves --dynamicThreshold=5 --constantThreshold=3 --predictionConfidenceThreshold=15 --enableValuePredForwarding --predictingArithmetic=1 --enableDynamicThreshold --forceNoTSO --uopCacheNumTicks=28 --dumpBranchDetail
#./build/X86/gem5.opt ./configs/example/se.py -c ./microbench --caches --l2cache --cpu-type=O3_X86_icelake_1   --mem-type=DDR4_2400_16x4 --mem-size=64GB --mem-channels=2  --enable-microop-cache --enable-micro-fusion --l3cache --forceNoTSO --uopCacheNumSets=24 --uopCacheNumWays=8 --uopCacheNumUops=6
#./build/X86/gem5.opt --outdir=m5out_lvp ./configs/example/se.py -c ./microbench --caches --l2cache --cpu-type=O3_X86_icelake_1   --mem-type=DDR4_2400_16x4 --mem-size=64GB --mem-channels=2  --enable-microop-cache  --enable-micro-fusion --l3cache --lvpredType=eves --dynamicThreshold=5 --constantThreshold=3 --predictionConfidenceThreshold=15 --enableValuePredForwarding --predictingArithmetic=1 --enableDynamicThreshold --forceNoTSO
#time ./build/X86/gem5.opt --outdir=m5out_raw --debug-flags=SuperOpSanityCheck --debug-file=raw_sanity.out ./configs/example/se.py -c ./microbench --caches --l2cache --cpu-type=O3_X86_icelake_1   --mem-type=DDR4_2400_16x4 --mem-size=64GB --mem-channels=2  --enable-microop-cache --enable-micro-fusion --l3cache >raw.out 2> raw.err
